version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '27081:80'
    container_name: wxcloud_pdf-extract-adobe-wxapp-backend-koanodejs
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=pdf-extract-adobe-wxapp-backend-koanodejs
      - role=container
    environment:
      - MYSQL_ADDRESS=127.0.0.1:3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=Mysql771527
      - MYSQL_ADDRESS=sh-cynosdbmysql-grp-ow2xsjyy.sql.tencentcdb.com:22214
networks:
  default:
    external:
      name: wxcb0
